name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          cache: "pipenv"
      - run: python -m pip install pipenv
      - run: pipenv install
      - run: make bootstrap
      - run: make check
      - run: make test
